# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build a docker image
      run: docker build --tag js-app:v1 .
    - name: run the image
      shell: bash
      run: docker run -d -p 3000:3000 js-app:v1
    - name: run the tests
      run: |
          export status=$(curl -i http://localhost:3000/ | awk 'NR == 1' | awk '{print $2}')
          if [ $status == 200 ]; then echo "Test Success"; else echo "Test Failed"; fi
          echo "Completed testing"
